title: Кайга
description: Сеттинг Cairn
theme: just-the-docs

url: https://onthotechnologist.github.io
baseurl: /kaiga

repository: onthotechnologist/kaiga

color_scheme: dark
search_enabled: true
heading_anchors: true

aux_links:
  Cairn RPG: https://cairnrpg.com
